# Generated by Django 2.0.5 on 2021-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0003_wholesaler_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='wsend_prequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wid', models.CharField(max_length=300)),
                ('wname', models.CharField(max_length=300)),
                ('pid', models.CharField(max_length=300)),
                ('vehicle_type', models.CharField(max_length=300)),
                ('brand_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
            ],
        ),
    ]
