# Generated by Django 2.0.5 on 2021-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesalers', '0004_wsend_prequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler_buy',
            name='product_price',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
