# Generated by Django 2.0.5 on 2021-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_retailer_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsend_prequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rid', models.CharField(max_length=300)),
                ('rname', models.CharField(max_length=300)),
                ('wid', models.CharField(max_length=300)),
                ('wname', models.CharField(max_length=300)),
                ('buyunid', models.CharField(max_length=300)),
                ('mainpid', models.CharField(max_length=300)),
                ('vehicle_type', models.CharField(max_length=300)),
                ('brand_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
            ],
        ),
    ]
