# Generated by Django 2.0.5 on 2021-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=300)),
                ('brand_name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('product_image', models.FileField(upload_to='')),
                ('mstatus', models.CharField(max_length=300)),
                ('pstatus', models.CharField(max_length=300)),
            ],
        ),
    ]
