# Generated by Django 2.0.5 on 2021-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='price',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
